# PYTHIA configuration file.
# Generated on 2020年 03月 02日 星期一 15:18:47 CST with the user supplied options:
# --with-hepmc2=/home/qliphy/Desktop/common/hepmc
# --with-root=/home/qliphy/Desktop/common/root6/

# Install directory prefixes.
PREFIX_BIN=/home/qliphy/Desktop/common/pythia8244/bin
PREFIX_INCLUDE=/home/qliphy/Desktop/common/pythia8244/include
PREFIX_LIB=/home/qliphy/Desktop/common/pythia8244/lib
PREFIX_SHARE=/home/qliphy/Desktop/common/pythia8244/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-O2  -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=
FASTJET3_LIB=

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/home/qliphy/Desktop/common/hepmc/bin
HEPMC2_INCLUDE=/home/qliphy/Desktop/common/hepmc/include
HEPMC2_LIB=/home/qliphy/Desktop/common/hepmc/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=

# LHAPDF6 configuration.
LHAPDF6_USE=false
LHAPDF6_BIN=
LHAPDF6_INCLUDE=
LHAPDF6_LIB=

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=true
ROOT_BIN=/home/qliphy/Desktop/common/root/bin/
ROOT_INCLUDE=/home/qliphy/Desktop/common/root/include/
ROOT_LIB=/home/qliphy/Desktop/common/root/lib/

# GZIP configuration.
GZIP_USE=false
GZIP_BIN=
GZIP_INCLUDE=
GZIP_LIB=

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=
BOOST_LIB=

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=
PYTHON_LIB=
